-- =========================
-- DROP TABLAS
-- =========================

PRAGMA FOREIGN_KEYS = OFF;

DROP TABLE IF EXISTS DETALLE_PEDIDO;
DROP TABLE IF EXISTS PEDIDO;
DROP TABLE IF EXISTS COMBO;
DROP TABLE IF EXISTS RESTAURANTE;
DROP TABLE IF EXISTS REPARTIDOR;
DROP TABLE IF EXISTS CLIENTE;
DROP TABLE IF EXISTS USUARIO;

PRAGMA FOREIGN_KEYS = ON;

-- =========================
-- TABLAS PRINCIPALES
-- =========================

CREATE TABLE USUARIO (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    EMAIL TEXT NOT NULL UNIQUE,
    PASSWORD_HASH TEXT NOT NULL,
    ROL TEXT NOT NULL CHECK (
        ROL IN ('CLIENTE', 'REPARTIDOR', 'ADMIN', 'RESTAURANTE')
    ),
    ESTADO INTEGER NOT NULL DEFAULT 1 CHECK (ESTADO IN (0, 1)),
    FECHA_REGISTRO TEXT NOT NULL DEFAULT (datetime('now'))
);

-- =========================
-- CLIENTE
-- =========================

CREATE TABLE CLIENTE (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,

    USUARIO_ID INTEGER NOT NULL UNIQUE,

    CEDULA TEXT NOT NULL UNIQUE,
    NOMBRE TEXT NOT NULL,
    DIRECCION TEXT NOT NULL,
    TELEFONO TEXT NOT NULL UNIQUE,
    TARJETA TEXT NOT NULL,

    FOREIGN KEY (USUARIO_ID)
        REFERENCES USUARIO(ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- =========================
-- REPARTIDOR
-- =========================

CREATE TABLE REPARTIDOR (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,

    USUARIO_ID INTEGER NOT NULL UNIQUE,

    CEDULA TEXT NOT NULL UNIQUE,
    NOMBRE TEXT NOT NULL,
    CORREO TEXT NOT NULL UNIQUE,
    DIRECCION TEXT NOT NULL,
    TELEFONO TEXT NOT NULL UNIQUE,
    TARJETA TEXT NOT NULL,

    ESTADO INTEGER NOT NULL DEFAULT 1
        CHECK (ESTADO IN (0, 1)),

    KM_RECORRIDOS_DIARIOS REAL NOT NULL DEFAULT 0,

    COSTO_KM_HABIL REAL NOT NULL DEFAULT 1000,
    COSTO_KM_FERIADO REAL NOT NULL DEFAULT 1500,

    AMONESTACIONES INTEGER NOT NULL DEFAULT 0
        CHECK (AMONESTACIONES >= 0 AND AMONESTACIONES <= 4),

    FOREIGN KEY (USUARIO_ID)
        REFERENCES USUARIO(ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- =========================
-- RESTAURANTE
-- =========================

CREATE TABLE RESTAURANTE (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,

    CEDULA_JURIDICA TEXT NOT NULL UNIQUE,
    NOMBRE TEXT NOT NULL,
    DIRECCION TEXT NOT NULL,
    TIPO_COMIDA TEXT NOT NULL,

    IMAGEN_URL TEXT,

    ESTADO INTEGER NOT NULL DEFAULT 1
        CHECK (ESTADO IN (0, 1))
);

-- =========================
-- COMBO
-- =========================

CREATE TABLE COMBO (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,

    RESTAURANTE_ID INTEGER NOT NULL,

    NUMERO_COMBO INTEGER NOT NULL,
    NOMBRE TEXT NOT NULL,
    DESCRIPCION TEXT,
    PRECIO REAL NOT NULL,

    IMAGEN_URL TEXT,

    ESTADO INTEGER NOT NULL DEFAULT 1
        CHECK (ESTADO IN (0, 1)),

    FOREIGN KEY (RESTAURANTE_ID)
        REFERENCES RESTAURANTE(ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CHECK (NUMERO_COMBO BETWEEN 1 AND 9)
);

-- =========================
-- PEDIDO
-- =========================

CREATE TABLE PEDIDO (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,

    CLIENTE_ID INTEGER NOT NULL,
    RESTAURANTE_ID INTEGER NOT NULL,
    REPARTIDOR_ID INTEGER,

    FECHA_CREACION TEXT NOT NULL DEFAULT (datetime('now')),
    FECHA_ENTREGA TEXT,

    ESTADO INTEGER NOT NULL DEFAULT 0
        CHECK (ESTADO IN (0, 1, 2, 3, 4)),

    DISTANCIA_KM REAL NOT NULL DEFAULT 0,

    FOREIGN KEY (CLIENTE_ID)
        REFERENCES CLIENTE(ID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    FOREIGN KEY (RESTAURANTE_ID)
        REFERENCES RESTAURANTE(ID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    FOREIGN KEY (REPARTIDOR_ID)
        REFERENCES REPARTIDOR(ID)
        ON DELETE SET NULL
        ON UPDATE CASCADE
);

-- ESTADO DEL PEDIDO:
-- 0 = CREADO (pedido registrado, aún sin preparación)
-- 1 = EN_PREPARACION (restaurante está preparando el pedido)
-- 2 = EN_CAMINO (repartidor asignado y en ruta)
-- 3 = ENTREGADO (pedido finalizado correctamente)
-- 4 = CANCELADO / SUSPENDIDO (pedido anulado por cliente, sistema o restricción)

-- =========================
-- DETALLE_PEDIDO
-- =========================

CREATE TABLE DETALLE_PEDIDO (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,

    PEDIDO_ID INTEGER NOT NULL,
    COMBO_ID INTEGER NOT NULL,

    CANTIDAD INTEGER NOT NULL DEFAULT 1
        CHECK (CANTIDAD > 0),

    PRECIO_UNITARIO REAL NOT NULL,

    CONFIGURACION TEXT,

    FOREIGN KEY (PEDIDO_ID)
        REFERENCES PEDIDO(ID)
        ON DELETE CASCADE,

    FOREIGN KEY (COMBO_ID)
        REFERENCES COMBO(ID)
        ON DELETE RESTRICT
);

-- CONFIGURACION -> JSON:
-- {"SIN_CEBOLLA": true, "BEBIDA": "GRANDE"}